apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatherer
spec:
  replicas: 4
  selector:
    matchLabels:
      component: gatherer
      type: ppo
  template:
    metadata:
      labels:
        component: gatherer
        type: ppo
    spec:
      containers:
        - name: gatherer
          image: localhost:5000/ppo
          command: [ "/bin/bash", "-c", "--" ]
          args: ["python3 /ppo/controller.py -g --redis-host=ppo-redis-master.default.svc.cluster.local"]
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            requests:
              cpu: 2
              memory: 4Gi
            limits:
              cpu: 2
              memory: 4Gi
