kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-volume-claim-tb
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      data: "rundir"