apiVersion: apps/v1
kind: Deployment
metadata:
  name: trainer
spec:
  replicas: 1
  selector:
    matchLabels:
      component: trainer
      type: ppo
  template:
    metadata:
      labels:
        component: trainer
        type: ppo
    spec:
      containers:
        - name: trainer
          image: 127.0.0.1:32000/ppo
          command: [ "/bin/bash", "-c", "--" ]
          args: ["python3 /ppo/controller.py -t --redis-host=fair-squirrel-redis-master.default.svc.cluster.local --redis-password=${REDIS_PASSWORD}"]
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fair-squirrel-redis
                  key: redis-password
          resources:
            limits:
              cpu: 2
